import { Feather } from '@expo/vector-icons';
import { useSignUp } from '@clerk/expo';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
export default function VerifyScreen() {
 const colors=useColors(), insets=useSafeAreaInsets(); const {signUp,fetchStatus}=useSignUp(); const [code,setCode]=useState(''); const [message,setMessage]=useState('');
 const verify=async()=>{setMessage(''); const {error}=await signUp.verifications.verifyEmailCode({code}); if(error)return setMessage('That code did not work. Please try again.'); if(signUp.status!=='complete')return setMessage('Please check the code and try again.'); await signUp.finalize({navigate:()=>router.replace('/create-pin')});};
 return <View style={[s.container,{backgroundColor:colors.background,paddingTop:insets.top+16}]}><Pressable onPress={()=>router.back()}><Feather name="arrow-left" size={21} color={colors.foreground}/></Pressable><View style={s.body}><Text style={[s.title,{color:colors.foreground}]}>Check your email.</Text><Text style={[s.subtitle,{color:colors.mutedForeground}]}>Enter the six-digit code we sent to verify your Travel & Land account.</Text><TextInput testID="verification-code" value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6} placeholder="000000" placeholderTextColor={colors.mutedForeground} style={[s.code,{color:colors.foreground,borderColor:colors.input,backgroundColor:colors.card}]}/>{!!message&&<Text style={[s.error,{color:colors.destructive}]}>{message}</Text>}<Pressable disabled={code.length!==6||fetchStatus==='fetching'} onPress={verify} style={[s.button,{backgroundColor:code.length===6?colors.primary:colors.muted}]}>{fetchStatus==='fetching'?<ActivityIndicator color={colors.primaryForeground}/>:<Text style={[s.buttonText,{color:colors.primaryForeground}]}>Verify email</Text>}</Pressable><Pressable onPress={()=>signUp.verifications.sendEmailCode()}><Text style={[s.resend,{color:colors.primary}]}>Send a new code</Text></Pressable></View></View>;
}
const s=StyleSheet.create({container:{flex:1,paddingHorizontal:22},body:{marginTop:105},title:{fontSize:29,fontWeight:'700'},subtitle:{fontSize:14,lineHeight:21,marginTop:10},code:{height:61,borderWidth:1,borderRadius:16,fontSize:25,fontWeight:'700',letterSpacing:10,textAlign:'center',marginTop:26},error:{fontSize:13,marginTop:10},button:{height:54,borderRadius:16,alignItems:'center',justifyContent:'center',marginTop:13},buttonText:{fontSize:14,fontWeight:'700'},resend:{textAlign:'center',fontSize:13,fontWeight:'700',marginTop:19}});